"""customer price and region preferences

Revision ID: 8705db077839
Revises: a3055dff0784
Create Date: 2026-09-01 17:18:15.058830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8705db077839'
down_revision: Union[str, None] = 'a3055dff0784'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('price_min', sa.Numeric(precision=16, scale=0), nullable=True))
    op.add_column('customer', sa.Column('price_max', sa.Numeric(precision=16, scale=0), nullable=True))
    op.add_column('customer', sa.Column('regions', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'regions')
    op.drop_column('customer', 'price_max')
    op.drop_column('customer', 'price_min')
    # ### end Alembic commands ###
