"""notice assignee_name

Revision ID: a3055dff0784
Revises: dc4741ec503a
Create Date: 2026-09-01 16:58:23.098176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3055dff0784'
down_revision: Union[str, None] = 'dc4741ec503a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notice', sa.Column('assignee_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notice', 'assignee_name')
    # ### end Alembic commands ###
